project_id = "iifgrxnkiejfvltzlvkd"

[functions.create-checkout]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.review-photo]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.import-dropbox-photos]
verify_jwt = false

[functions.batch-import-users]
verify_jwt = false

[functions.import-case-study-attachments]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-training-invite]
verify_jwt = false

[functions.send-training-reminders]
verify_jwt = false
